openapi: 3.0.0
info:
  title: API de Consulta de Mensajes Activos
  version: 1.0.0
paths:
  /message:
    post:
      summary: Obtener cantidad de mensajes activos
      requestBody:
        required: true
        content:
          application/json:
            example:
              nombreCliente: null
              mes: 2
      responses:
        '200':
          description: Cantidad de mensajes activos listados con éxito
          content:
            application/json:
              example:
                success: true
                message: "Cantidad de mensajes activos listados con éxito"
                body:
                  - estadoEnvio: 1
                    cantidad: 2
                  - estadoEnvio: 2
                    cantidad: 4
                  - estadoEnvio: 3
                    cantidad: 4
  /campania:
    post:
      summary: Insertar nueva campaña
      requestBody:
        required: true
        content:
          application/json:
            example:
              nombre: "Ambiente"
              idUsuario: 1
              fechaHoraProgramacion: "2022-01-01"
              estado: 1
      responses:
        '200':
          description: Campaña insertada con éxito
          content:
            application/json:
              example:
                success: true
                message: "Campaña insertada con éxito"
                body: []