service: aws-project-crud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getMessages:
    handler: src/handler.post
    events:
      - httpApi:
          path: /message
          method: post
  insertCampania:
    handler: src/handler.postCampania
    events:
      - httpApi:
          path: /campania
          method: post
  getUsuarios:
    handler: src/handler.getUsuarios
    events:
      - httpApi:
          path: /usuarios
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
